[debug] [2020-04-12T15:02:16.254Z] ----------------------------------------------------------------------
[debug] [2020-04-12T15:02:16.258Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Anmol\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2020-04-12T15:02:16.259Z] CLI Version:   8.0.2
[debug] [2020-04-12T15:02:16.259Z] Platform:      win32
[debug] [2020-04-12T15:02:16.259Z] Node Version:  v12.14.1
[debug] [2020-04-12T15:02:16.260Z] Time:          Sun Apr 12 2020 20:32:16 GMT+0530 (India Standard Time)
[debug] [2020-04-12T15:02:16.261Z] ----------------------------------------------------------------------
[debug] [2020-04-12T15:02:16.261Z] 
[debug] [2020-04-12T15:02:16.293Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-12T15:02:16.380Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (C:\Users\Anmol\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async GoogleAuth.getClient (C:\Users\Anmol\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\Anmol\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
